name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Mojo (Placeholder)
        run: |
          echo "Installing Mojo (placeholder)..."
          # Add Mojo installation steps here when development starts
          echo "Skipping actual installation for now."

      - name: Verify Setup
        run: |
          echo "Environment is ready. Waiting for actual project files."

  placeholder-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Placeholder for API Worker Build
        run: |
          echo "No API worker code available yet. Skipping build."

      - name: Placeholder for AI Worker Build
        run: |
          echo "No AI worker code available yet. Skipping build."

  placeholder-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Placeholder for Tests
        run: |
          echo "No test cases available yet. Skipping tests."
